In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

from sklearn.model_selection import train_test_split
from sklearn import datasets

from collections import Counter

In [ ]:
class KNN:
    def __init__(self, k=3):
        self.k = k 
        
    def euclidean_distance(x1, x2):
        return np.sqrt(np.sum((x1 - x2) ** 2))
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
    def predict(self, X):
        y_pred = [self._predict(x) for x in x]
        return np.array(y_pred)
    
    def _predict(self, x):
        distances = [self.euclidean_distance(x, x_train) for x_train in self.X]
        k_idx = np.argsort(distances)[: self.k]

In [13]:
a = [6,5,7,8,9,2,3,4,5,6,78,6,5,6,77,5,76,7,66,66,]

In [14]:
np.argsort(a)

array([ 5,  6,  7,  1, 15, 12,  8,  0, 13, 11,  9,  2, 17,  3,  4, 18, 19,
       16, 14, 10])

In [15]:
np.argsort(a)[1 : 3]

array([6, 7])

In [9]:
len(a)

20

In [12]:
np.argsort([4,3,5,2,1])

array([4, 3, 1, 0, 2])